# Generated by Django 6.0.4 on 2026-05-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beverages',
            new_name='Beverage',
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.CharField(choices=[('g', 'Gramas'), ('ml', 'Mililitros'), ('un', 'Unidades/Fatias')], max_length=8),
        ),
    ]
