# Generated by Django 6.0.4 on 2026-05-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="dish",
        ),
        migrations.RemoveField(
            model_name="historicaldish",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicaldish",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="historicaldish",
            name="product_ptr",
        ),
        migrations.RemoveField(
            model_name="historicalnondish",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalnondish",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="historicalnondish",
            name="product_ptr",
        ),
        migrations.RemoveField(
            model_name="historicalnondish",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="historicalproduct",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalproduct",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="nondish",
            name="product_ptr",
        ),
        migrations.RemoveField(
            model_name="nondish",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingredient",
        ),
        migrations.DeleteModel(
            name="Dish",
        ),
        migrations.DeleteModel(
            name="HistoricalDish",
        ),
        migrations.DeleteModel(
            name="HistoricalNonDish",
        ),
        migrations.DeleteModel(
            name="HistoricalProduct",
        ),
        migrations.DeleteModel(
            name="NonDish",
        ),
    ]
