# Generated by Django 6.0.4 on 2026-05-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalbeverage",
            old_name="qty_sold",
            new_name="total_sold",
        ),
        migrations.RenameField(
            model_name="historicalburger",
            old_name="qty_sold",
            new_name="total_sold",
        ),
        migrations.RenameField(
            model_name="historicalproduct",
            old_name="qty_sold",
            new_name="total_sold",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="qty_sold",
            new_name="total_sold",
        ),
    ]
