# Generated by Django 6.0.4 on 2026-05-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0002_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sold",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
