# Generated by Django 6.0.4 on 2026-05-10 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0003_alter_stock_price_alter_stock_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
    ]
