# Generated by Django 6.0.4 on 2026-05-10 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0004_remove_recipe_ingredients"),
        ("Recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="burger",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="Recipe.recipe"
            ),
        ),
        migrations.RemoveField(
            model_name="recipeitems",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="recipeitems",
            name="ingredient",
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
        migrations.DeleteModel(
            name="RecipeItems",
        ),
    ]
