# Generated by Django 6.0.4 on 2026-05-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0004_historicalproduct_historicalstock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="sold",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="sold",
            field=models.IntegerField(blank=True),
        ),
    ]
