# Generated by Django 6.0.4 on 2026-05-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0005_alter_historicalproduct_sold_alter_product_sold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="sold",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="sold",
            field=models.IntegerField(default=0),
        ),
    ]
