# Generated by Django 6.0.4 on 2026-05-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sales", "0003_alter_orderitem_product"),
        ("Inventory", "0002_remove_recipe_dish_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
    ]
