# Generated by Django 6.0.4 on 2026-05-18 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category_type', models.CharField(choices=[('DISH', 'Pratos (Produtos com receitas)'), ('NONDISH', 'Outros (Estoque direto)')], max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'unique_together': {('name', 'category_type')},
            },
        ),
        migrations.AddField(
            model_name='historicaldish',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Menu.category'),
        ),
        migrations.AddField(
            model_name='historicalnondish',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Menu.category'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Menu.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Menu.category'),
        ),
    ]
