name: Semantic Release

on:
  push:
    branches:
      - main  

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.14.4" 


    - name: Install Semantic Release
      run: |
        pip install python-semantic-release


    - name: Run Semantic Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Set git user configs so the tool can sign the automated release commits
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Execute the official release
        semantic-release version