# Generated by Django 6.0.4 on 2026-05-15 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Cashier", "0001_initial"),
        ("Inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="Inventory.product"
            ),
        ),
    ]
