# Generated by Django 6.0.4 on 2026-05-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cashier", "0004_alter_historicalorder_total_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorder",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
