# Generated by Django 6.0.4 on 2026-05-13 05:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cashier", "0005_alter_historicalorder_total_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalorder",
            old_name="is_processed",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="is_processed",
            new_name="status",
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
    ]
