# Generated by Django 6.0.4 on 2026-05-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cashier", "0006_rename_is_processed_historicalorder_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
